#include <QString>

static const QString IP = "172-17-0-1_192-168-100-21";

static const QString json_no_component {
"{\n"
"    \"appType\" : \"DSMonitor\",\n"
"    \"msgType\" : \"Status\",\n"
"    \"Network\" : {\n"
"        \"Gateway\" : \"192.168.100.255\",\n"
"        \"IPv4\" : \"192.168.100.21\",\n"
"        \"Mask\" : \"255.255.255.0\",\n"
"        \"hostName\" : \"be3yh4uk\",\n"
"        \"interface\" : \"enp34s0\"\n"
"    },\n"
"    \"Cpu\" : {\n"
"        \"cache\" : \"Level 1 (Data) 32KB, 8-way set-associative, 64 sets\\nLevel 1 (Instruction) 32KB, 8-way set-associative, 64 sets\\nLevel 2 (Unified) 512KB, 8-way set-associative, 1024 sets\\nLevel 3 (Unified) 16384KB, 16-way set-associative, 16384 sets\\n\",\n"
"        \"cores\" : \"8\",\n"
"        \"max\" : \"3600\",\n"
"        \"min\" : \"2200\",\n"
"        \"name\" : \"AMD Ryzen 7 3700X 8-Core Processor\",\n"
"        \"threads\" : \"16\",\n"
"        \"usage\" : \"3.73317\"\n"
"    },\n"
"    \"Memory\" : {\n"
"        \"free\" : \"3057340\",\n"
"        \"load\" : \"9\",\n"
"        \"total\" : \"32871468\",\n"
"        \"used\" : \"29814128\"\n"
"    },\n"
"    \"Storage\" : {\n"
"        \"available\" : \"146396758016\",\n"
"        \"device\" : \"\\/dev\\/sdc1\",\n"
"        \"free\" : \"168265539584\",\n"
"        \"load\" : \"33.3333\",\n"
"        \"path\" : \"\\/home\",\n"
"        \"total\" : \"471490117632\",\n"
"        \"type\" : \"ext4\",\n"
"        \"used\" : \"303224578048\"\n"
"    },\n"
"    \"System\" : {\n"
"        \"architecture\" : \"x86_64\",\n"
"        \"id\" : \"ubuntu\",\n"
"        \"kernelType\" : \"be3yh4uk\",\n"
"        \"productName\" : \"Linux\"\n"
"    },\n"
"    \"Process\" : [\n"
"        {\n"
"            \"Process\" : {\n"
"                \"name\" : \"Application_0\",\n"
"                \"path\" : \"..\\/..\\/Application_0\\/exe\\/Application_0\\u0000\",\n"
"                \"pid\" : \"1038589\",\n"
"                \"ppid\" : \"1038577\",\n"
"                \"status\" : \"true\",\n"
"                \"threads\" : \"3\",\n"
"                \"usageCPU\" : \"0.00982704\",\n"
"                \"userName\" : \"#!Be3yH4uK,,,\",\n"
"                \"workingSetSize\" : \"23100\"\n"
"            },\n"
"            \"Threads\" : {\n"
"                \"memoryLoad\" : \"2.29852e-06\",\n"
"                \"pid\" : \"1038589\",\n"
"                \"ppid\" : \"1038577\",\n"
"                \"usage\" : \"0\"\n"
"            },\n"
"            \"Xml\" : {\n"
"                \"key\" : \"Application_0\",\n"
"                \"path\" : \"..\\/..\\/Application_0\\/exe\\/\",\n"
"                \"xml\" : \"<root>\\r\\n    <ApplicationPath>..\\/..\\/Application_0<\\/ApplicationPath>\\r\\n    <DSHost>DSHost<\\/DSHost>\\r\\n<\\/root>\\r\\n\"\n"
"            }\n"
"        },\n"
"        {\n"
"            \"Process\" : {\n"
"                \"name\" : \"Application_1\",\n"
"                \"path\" : \"..\\/..\\/Application_1\\/exe\\/Application_1\\u0000\",\n"
"                \"pid\" : \"1038590\",\n"
"                \"ppid\" : \"1038577\",\n"
"                \"status\" : \"true\",\n"
"                \"threads\" : \"3\",\n"
"                \"usageCPU\" : \"0.00982704\",\n"
"                \"userName\" : \"#!Be3yH4uK,,,\",\n"
"                \"workingSetSize\" : \"23316\"\n"
"            },\n"
"            \"Threads\" : {\n"
"                \"memoryLoad\" : \"2.32002e-06\",\n"
"                \"pid\" : \"1038590\",\n"
"                \"ppid\" : \"1038577\",\n"
"                \"usage\" : \"0.00982704\"\n"
"            },\n"
"            \"Xml\" : {\n"
"                \"key\" : \"Application_1\",\n"
"                \"path\" : \"..\\/..\\/Application_1\\/exe\\/\",\n"
"                \"xml\" : \"<root>\\r\\n    <ApplicationPath>..\\/..\\/Application_1<\\/ApplicationPath>\\r\\n    <DSHost>DSHost<\\/DSHost>\\r\\n<\\/root>\\r\\n\"\n"
"            }\n"
"        }\n"
"    ]\n"
"}"
};

static const QString json_component_2 {
"{\n"
"    \"appType\" : \"DSMonitor\",\n"
"    \"msgType\" : \"Status\",\n"
"    \"Network\" : {\n"
"        \"Gateway\" : \"192.168.100.255\",\n"
"        \"IPv4\" : \"192.168.100.21\",\n"
"        \"Mask\" : \"255.255.255.0\",\n"
"        \"hostName\" : \"be3yh4uk\",\n"
"        \"interface\" : \"enp34s0\"\n"
"    },\n"
"    \"Cpu\" : {\n"
"        \"cache\" : \"Level 1 (Data) 32KB, 8-way set-associative, 64 sets\\nLevel 1 (Instruction) 32KB, 8-way set-associative, 64 sets\\nLevel 2 (Unified) 512KB, 8-way set-associative, 1024 sets\\nLevel 3 (Unified) 16384KB, 16-way set-associative, 16384 sets\\n\",\n"
"        \"cores\" : \"8\",\n"
"        \"max\" : \"3600\",\n"
"        \"min\" : \"2200\",\n"
"        \"name\" : \"AMD Ryzen 7 3700X 8-Core Processor\",\n"
"        \"threads\" : \"16\",\n"
"        \"usage\" : \"3.73317\"\n"
"    },\n"
"    \"Memory\" : {\n"
"        \"free\" : \"3057340\",\n"
"        \"load\" : \"9\",\n"
"        \"total\" : \"32871468\",\n"
"        \"used\" : \"29814128\"\n"
"    },\n"
"    \"Storage\" : {\n"
"        \"available\" : \"146396758016\",\n"
"        \"device\" : \"\\/dev\\/sdc1\",\n"
"        \"free\" : \"168265539584\",\n"
"        \"load\" : \"33.3333\",\n"
"        \"path\" : \"\\/home\",\n"
"        \"total\" : \"471490117632\",\n"
"        \"type\" : \"ext4\",\n"
"        \"used\" : \"303224578048\"\n"
"    },\n"
"    \"System\" : {\n"
"        \"architecture\" : \"x86_64\",\n"
"        \"id\" : \"ubuntu\",\n"
"        \"kernelType\" : \"be3yh4uk\",\n"
"        \"productName\" : \"Linux\"\n"
"    },\n"
"    \"Process\" : [\n"
"        {\n"
"            \"Process\" : {\n"
"                \"name\" : \"Application_0\",\n"
"                \"error\" : \"not running\"\n"
"            },\n"
"            \"Threads\" : {\n"
"                \"memoryLoad\" : \"2.32002e-06\",\n"
"                \"pid\" : \"1038590\",\n"
"                \"ppid\" : \"1038577\",\n"
"                \"usage\" : \"0.00982704\"\n"
"            },\n"
"            \"Xml\" : {\n"
"                \"key\" : \"Application_1\",\n"
"                \"path\" : \"..\\/..\\/Application_1\\/exe\\/\",\n"
"                \"xml\" : \"<root>\\r\\n    <ApplicationPath>..\\/..\\/Application_1<\\/ApplicationPath>\\r\\n    <DSHost>DSHost<\\/DSHost>\\r\\n<\\/root>\\r\\n\"\n"
"            }\n"
"        },\n"
"        {\n"
"            \"Process\" : {\n"
"                \"name\" : \"Application_1\",\n"
"                \"path\" : \"..\\/..\\/Application_1\\/exe\\/Application_1\\u0000\",\n"
"                \"pid\" : \"1038590\",\n"
"                \"ppid\" : \"1038577\",\n"
"                \"status\" : \"true\",\n"
"                \"threads\" : \"3\",\n"
"                \"usageCPU\" : \"0.00982704\",\n"
"                \"userName\" : \"#!Be3yH4uK,,,\",\n"
"                \"workingSetSize\" : \"23316\"\n"
"            },\n"
"            \"Threads\" : {\n"
"                \"memoryLoad\" : \"2.32002e-06\",\n"
"                \"pid\" : \"1038590\",\n"
"                \"ppid\" : \"1038577\",\n"
"                \"usage\" : \"0.00982704\"\n"
"            },\n"
"            \"Xml\" : {\n"
"                \"key\" : \"Application_1\",\n"
"                \"path\" : \"..\\/..\\/Application_1\\/exe\\/\",\n"
"                \"xml\" : \"<root>\\r\\n    <ApplicationPath>..\\/..\\/Application_1<\\/ApplicationPath>\\r\\n    <DSHost>DSHost<\\/DSHost>\\r\\n<\\/root>\\r\\n\"\n"
"            }\n"
"        }\n"
"    ]\n"
"}"
};

static const QString json_component_error {
"{\n"
"    \"appType\" : \"DSMonitor\",\n"
"    \"msgType\" : \"Status\",\n"
"    \"Network\" : {\n"
"        \"Gateway\" : \"192.168.100.255\",\n"
"        \"IPv4\" : \"192.168.100.21\",\n"
"        \"Mask\" : \"255.255.255.0\",\n"
"        \"hostName\" : \"be3yh4uk\",\n"
"        \"interface\" : \"enp34s0\"\n"
"    },\n"
"    \"Cpu\" : {\n"
"        \"cache\" : \"Level 1 (Data) 32KB, 8-way set-associative, 64 sets\\nLevel 1 (Instruction) 32KB, 8-way set-associative, 64 sets\\nLevel 2 (Unified) 512KB, 8-way set-associative, 1024 sets\\nLevel 3 (Unified) 16384KB, 16-way set-associative, 16384 sets\\n\",\n"
"        \"cores\" : \"8\",\n"
"        \"max\" : \"3600\",\n"
"        \"min\" : \"2200\",\n"
"        \"name\" : \"AMD Ryzen 7 3700X 8-Core Processor\",\n"
"        \"threads\" : \"16\",\n"
"        \"usage\" : \"3.73317\"\n"
"    },\n"
"    \"Memory\" : {\n"
"        \"free\" : \"3057340\",\n"
"        \"load\" : \"9\",\n"
"        \"total\" : \"32871468\",\n"
"        \"used\" : \"29814128\"\n"
"    },\n"
"    \"Storage\" : {\n"
"        \"available\" : \"146396758016\",\n"
"        \"device\" : \"\\/dev\\/sdc1\",\n"
"        \"free\" : \"168265539584\",\n"
"        \"load\" : \"33.3333\",\n"
"        \"path\" : \"\\/home\",\n"
"        \"total\" : \"471490117632\",\n"
"        \"type\" : \"ext4\",\n"
"        \"used\" : \"303224578048\"\n"
"    },\n"
"    \"System\" : {\n"
"        \"architecture\" : \"x86_64\",\n"
"        \"id\" : \"ubuntu\",\n"
"        \"kernelType\" : \"be3yh4uk\",\n"
"        \"productName\" : \"Linux\"\n"
"    },\n"
"    \"Process\" : [\n"
"    ]\n"
"}"
};

static QString test_1 = "{\n    \"appType\" : \"DSMonitor\",\n    \"msgType\" : \"Status\",\n    \"Network\" : {\n    "
                        "    \"Gateway\" : \"192.168.100.255\",\n        \"IPv4\" : \"192.168.100.21\",\n        "
                        "\"Mask\" : \"255.255.255.0\",\n        \"hostName\" : \"be3yh4uk\",\n        \"interface\" :"
                        " \"enp34s0\"\n    },\n    \"Cpu\" : {\n        \"cache\" : \"Level 1 (Data) 32KB, 8-way set-associative, 64 sets\\nLevel 1 (Instruction) 32KB, 8-way set-associative, 64 sets\\nLevel 2 (Unified) 512KB, 8-way set-associative, 1024 sets\\nLevel 3 (Unified) 16384KB, 16-way set-associative, 16384 sets\\n\",\n        \"cores\" : \"8\",\n        \"max\" : \"3600\",\n        \"min\" : \"2200\",\n        \"name\" : \"AMD Ryzen 7 3700X 8-Core Processor\",\n        \"threads\" : \"16\",\n        \"usage\" : \"15.608\"\n    },\n    \"Memory\" : {\n        \"free\" : \"6800960\",\n        \"load\" : \"20\",\n        \"total\" : \"32871468\",\n        \"used\" : \"26070508\"\n    },\n    \"Storage\" : {\n        \"available\" : \"124236574720\",\n        \"device\" : \"\\/dev\\/sdc1\",\n        \"free\" : \"146105356288\",\n        \"load\" : \"33.3333\",\n        \"path\" : \"\\/home\",\n        \"total\" : \"471490117632\",\n        \"type\" : \"ext4\",\n        \"used\" : \"325384761344\"\n    },\n    \"System\" : {\n        \"architecture\" : \"x86_64\",\n        \"id\" : \"ubuntu\",\n        \"kernelType\" : \"Linux\",\n        \"productName\" : \"\\\"20.04.2 LTS (Focal Fossa)\\\"\"\n    },\n    \"Process\" : [\n        {\n            \"Process\" : {\n                \"memoryLoad\" : \"1.07069e-06\",\n                \"name\" : \"Application_0\",\n                \"path\" : \"..\\/..\\/Application_0\\/exe\\/Application_0\\u0000\",\n                \"pid\" : \"1275656\",\n                \"ppid\" : \"1271884\",\n                \"status\" : \"true\",\n                \"threads\" : \"3\",\n                \"usageCPU\" : \"0.0254065\",\n                \"userName\" : \"#!Be3yH4uK,,,\",\n                \"workingSetSize\" : \"23936\"\n            },\n            \"Threads\" : [\n                {\n                    \"pid\" : \"1275650\",\n                    \"ppid\" : \"1271884\",\n                    \"usage\" : \"0.0254065\"\n                },\n                {\n                    \"pid\" : \"1275657\",\n                    \"ppid\" : \"1271884\",\n                    \"usage\" : \"0\"\n                },\n                {\n                    \"pid\" : \"1275658\",\n                    \"ppid\" : \"1271884\",\n                    \"usage\" : \"0\"\n                }\n            ],\n            \"Xml\" : {\n                \"key\" : \"Application_0\",\n                \"path\" : \"..\\/..\\/Application_0\\/exe\\/\",\n                \"xml\" : \"<root>\\r\\n    <ApplicationPath>..\\/..\\/Application_0<\\/ApplicationPath>\\r\\n    <DSHost>DSHost<\\/DSHost>\\r\\n<\\/root>\\r\\n\"\n            }\n        }\n    ]\n}";

static QString test_2 = "{\n    \"appType\" : \"DSMonitor\",\n    \"msgType\" : \"Status\",\n    \"Network\" : {\n    "
                        "    \"Gateway\" : \"192.168.100.255\",\n        \"IPv4\" : \"192.168.100.21\",\n        "
                        "\"Mask\" : \"255.255.255.0\",\n        \"hostName\" : \"be3yh4uk\",\n        \"interface\" :"
                        " \"enp34s0\"\n    },\n    \"Cpu\" : {\n        \"cache\" : \"Level 1 (Data) 32KB, 8-way set-associative, 64 sets\\nLevel 1 (Instruction) 32KB, 8-way set-associative, 64 sets\\nLevel 2 (Unified) 512KB, 8-way set-associative, 1024 sets\\nLevel 3 (Unified) 16384KB, 16-way set-associative, 16384 sets\\n\",\n        \"cores\" : \"8\",\n        \"max\" : \"3600\",\n        \"min\" : \"2200\",\n        \"name\" : \"AMD Ryzen 7 3700X 8-Core Processor\",\n        \"threads\" : \"16\",\n        \"usage\" : \"15.608\"\n    },\n    \"Memory\" : {\n        \"free\" : \"6800960\",\n        \"load\" : \"20\",\n        \"total\" : \"32871468\",\n        \"used\" : \"26070508\"\n    },\n    \"Storage\" : {\n        \"available\" : \"124236574720\",\n        \"device\" : \"\\/dev\\/sdc1\",\n        \"free\" : \"146105356288\",\n        \"load\" : \"33.3333\",\n        \"path\" : \"\\/home\",\n        \"total\" : \"471490117632\",\n        \"type\" : \"ext4\",\n        \"used\" : \"325384761344\"\n    },\n    \"System\" : {\n        \"architecture\" : \"x86_64\",\n        \"id\" : \"ubuntu\",\n        \"kernelType\" : \"Linux\",\n        \"productName\" : \"\\\"20.04.2 LTS (Focal Fossa)\\\"\"\n    },\n    \"Process\" : [\n        {\n            \"Process\" : {\n                \"memoryLoad\" : \"1.07069e-06\",\n                \"name\" : \"Application_0\",\n                \"path\" : \"..\\/..\\/Application_0\\/exe\\/Application_0\\u0000\",\n                \"pid\" : \"1275651\",\n                \"ppid\" : \"1271884\",\n                \"status\" : \"true\",\n                \"threads\" : \"3\",\n                \"usageCPU\" : \"0.0254065\",\n                \"userName\" : \"#!Be3yH4uK,,,\",\n                \"workingSetSize\" : \"23936\"\n            },\n            \"Threads\" : [\n                {\n                    \"pid\" : \"1275656\",\n                    \"ppid\" : \"1271884\",\n                    \"usage\" : \"0.0254065\"\n                },\n                {\n                    \"pid\" : \"1275657\",\n                    \"ppid\" : \"1271884\",\n                    \"usage\" : \"0\"\n                },\n                {\n                    \"pid\" : \"1275658\",\n                    \"ppid\" : \"1271884\",\n                    \"usage\" : \"0\"\n                }\n            ],\n            \"Xml\" : {\n                \"key\" : \"Application_0\",\n                \"path\" : \"..\\/..\\/Application_0\\/exe\\/\",\n                \"xml\" : \"<root>\\r\\n    <ApplicationPath>..\\/..\\/Application_0<\\/ApplicationPath>\\r\\n    <DSHost>DSHost<\\/DSHost>\\r\\n<\\/root>\\r\\n\"\n            }\n        }\n    ]\n}";

static QString test_3 = "{\n    \"appType\" : \"DSMonitor\",\n    \"msgType\" : \"Status\",\n    \"Network\" : {\n    "
                        "    \"Gateway\" : \"192.168.100.255\",\n        \"IPv4\" : \"192.168.100.21\",\n        "
                        "\"Mask\" : \"255.255.255.0\",\n        \"hostName\" : \"be3yh4uk\",\n        \"interface\" :"
                        " \"enp34s0\"\n    },\n    \"Cpu\" : {\n        \"cache\" : \"Level 1 (Data) 32KB, 8-way set-associative, 64 sets\\nLevel 1 (Instruction) 32KB, 8-way set-associative, 64 sets\\nLevel 2 (Unified) 512KB, 8-way set-associative, 1024 sets\\nLevel 3 (Unified) 16384KB, 16-way set-associative, 16384 sets\\n\",\n        \"cores\" : \"8\",\n        \"max\" : \"3600\",\n        \"min\" : \"2200\",\n        \"name\" : \"AMD Ryzen 7 3700X 8-Core Processor\",\n        \"threads\" : \"16\",\n        \"usage\" : \"15.608\"\n    },\n    \"Memory\" : {\n        \"free\" : \"6800960\",\n        \"load\" : \"20\",\n        \"total\" : \"32871468\",\n        \"used\" : \"26070508\"\n    },\n    \"Storage\" : {\n        \"available\" : \"124236574720\",\n        \"device\" : \"\\/dev\\/sdc1\",\n        \"free\" : \"146105356288\",\n        \"load\" : \"33.3333\",\n        \"path\" : \"\\/home\",\n        \"total\" : \"471490117632\",\n        \"type\" : \"ext4\",\n        \"used\" : \"325384761344\"\n    },\n    \"System\" : {\n        \"architecture\" : \"x86_64\",\n        \"id\" : \"ubuntu\",\n        \"kernelType\" : \"Linux\",\n        \"productName\" : \"\\\"20.04.2 LTS (Focal Fossa)\\\"\"\n    },\n    \"Process\" : [\n        {\n            \"Process\" : {\n                \"memoryLoad\" : \"1.07069e-06\",\n                \"name\" : \"Application_0\",\n                \"path\" : \"..\\/..\\/Application_0\\/exe\\/Application_0\\u0000\",\n                \"pid\" : \"1275652\",\n                \"ppid\" : \"1271884\",\n                \"status\" : \"true\",\n                \"threads\" : \"3\",\n                \"usageCPU\" : \"0.0254065\",\n                \"userName\" : \"#!Be3yH4uK,,,\",\n                \"workingSetSize\" : \"23936\"\n            },\n            \"Threads\" : [\n                {\n                    \"pid\" : \"1275656\",\n                    \"ppid\" : \"1271884\",\n                    \"usage\" : \"0.0254065\"\n                },\n                {\n                    \"pid\" : \"1275657\",\n                    \"ppid\" : \"1271884\",\n                    \"usage\" : \"0\"\n                },\n                {\n                    \"pid\" : \"1275658\",\n                    \"ppid\" : \"1271884\",\n                    \"usage\" : \"0\"\n                }\n            ],\n            \"Xml\" : {\n                \"key\" : \"Application_0\",\n                \"path\" : \"..\\/..\\/Application_0\\/exe\\/\",\n                \"xml\" : \"<root>\\r\\n    <ApplicationPath>..\\/..\\/Application_0<\\/ApplicationPath>\\r\\n    <DSHost>DSHost<\\/DSHost>\\r\\n<\\/root>\\r\\n\"\n            }\n        }\n    ]\n}";